name: Testery Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TESTERY_TOKEN: ${{ secrets.TesteryTokenProd }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install testery --upgrade
      - name: Run Testery Tests
        run: |
          testery create-test-run --api-url https://api.testery.io/api --token "$TESTERY_TOKEN" --git-ref "$GITHUB_SHA" --project "example-webdriverio"
